sudo: required
git:
  depth: false
services:
- docker
- heroku
language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_9f97bc52c395_key -iv $encrypted_9f97bc52c395_iv
  -in .netrc.enc -out .netrc -d
- git clone https://github.com/pkoniu/iosr-2017-deployment.git
- sh iosr-2017-deployment/before_install.sh
install:
- npm install
before_script:
- npm test
script:
- sh iosr-2017-deployment/script.sh
after_success:
- sh iosr-2017-deployment/after_success.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=orders
  - HEROKU_APP_NAME=iosr2017orders
  - secure: q1ilJHZngKwAi7ft4WWFkkJnSW3R6Bxo9kZEsSuz3+CoPVvpgnc9plfCKGgqDVDhdhkgxpYi5BRhXvkrcaYA21j37WsbGeTtvBVjuqEQHDcQh0aCeeBtn60enbVuVump1Wfiu12ko0O4wddhZeabKOI1XobyjwoYu6aorQEtQ5ggHvX27R49MnYgtBemcY4XUZkrzPzkAR2YfLr8nDPUutC3/rRVJPMO12XIqJFxsLMx5ia5wD7cHA0WWogJ4xJIF1gcA2R258p0Y6UB7AvMQMRx1b2SqRUhb36twYGU1PlFlIt/yNrzg/9mj84pnmGsR6rnPD29ryX0q6T6s5y2Q+x2ZFWwZRGp0cqBXf4ckce0ZzzXiY2DMmRTCh8cGkNNbJxVCpVEJkSJjJT5a1TG+UtnM1ZdULDxm7NF1ZnIkS5mDfE8jymiTqOPcGlhK/4yAOUTLsK+6WqVvC2uIfo15TyOMLGB0OEm7tL3GHo1Mp6mgcP3CTpPv5laZkGnLuQwxmwVEAsQeqZlPfDALfe3eYLfitWg8lT7bGTQ3uTLHaIB9TD18CJlthHPXz5L5+Rwov8QDbHqpp9UJNjROjtv4O6b45mfd1EQCGcg7D448AjRyNaShfZJ09WS/jsYPPgbxzuehG3QpooSMrgAH4Xv8ain8BVCFHs7aPrauzz0Im4=
  - secure: ifv/zDB5tTY2hOydsHmogM69OpFLKAOyHklSZMzYTHNVCnHfL2hnENEvbxoZBVxRzZwMtioCzdFtGMnlHUSW14DOqxIsJsktyQ5T6qCB3MF/qpdScT4L0wPULRqOhHs0DVOYSOCQeWqhmg47mkdxzieZQp/Vri+MA3sI0uxLwu8u+jwcJmDGnor9iy2ZvVrUyLgtu8s3+nTCQY7oLjxLdN8CAx+CMv/qEYKWTxWU4jpXhXg2Bllxgvy5lCvz5z5P0hWlpINM7kC4lIXdBN2VWGJrOb0MF+0Vi0isekc/Gvq5QVH72oOmbUZWYeGC9TWXGoAZOb0HQL9a24WQlBCY1G9mppWbcGnaLT1tL09hLWO1Cv5HhYCOCkqsVe3bMbzPtKKooOerBbZQuhFFhN5yVIGIfrAUdlmcY1fe+O8QjW0XxUdMBVWLypDdHrKfDsKux2oBcua/4M+DLzqYt3s04j++IliR+m3cpt8ufbBWioe98XiZ8klUCKBpht2TJLb1nMso3VBQkpdRt0QPuJRfAytP78OO+NlBO9Rp36fO0YPQa75rX/zemo2rFzMFIkPLO2Cr7+EPE5mCPkUh1oWoqL4JeA1Qx3UDGVdCOnCnsOw7Of+kzXJudRYyHwkNL3gXLASmISZrkIyx4z4jMlcYFYNS7pdmjAQ2bnR0nHnGThk=
