sudo: required
git:
  depth: false
services:
- docker
- heroku
language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_9f97bc52c395_key -iv $encrypted_9f97bc52c395_iv
  -in .netrc.enc -out .netrc -d
- git clone https://github.com/pkoniu/iosr-2017-deployment.git
- sh iosr-2017-deployment/before_install.sh
install:
- npm install
before_script:
- npm test
script:
- sh iosr-2017-deployment/script.sh
after_success:
- sh iosr-2017-deployment/after_success.sh
env:
  global:
  - DOCKER_USER=iosr2017
  - DOCKER_REPO=orders
  - HEROKU_APP_NAME=iosr2017orders
  - secure: XKcKmi5f7dGgVsMMxTLmHDYkL2qffZBJXtIaojHETG7Q5MCeRwi5scesEyXUPyXQn1V2b2tgXI3F92qxk4Uwuscr9eQbpTwDGAEf/Qq6v1dtwwwtI2K1Ar4ULor5gfvZ+GsuUdq9Gq1g84xVgtaWyIM5daEzSShxZWW2tsdESEllZP6ouDtgOiAQx+SbmeqnAqjw4UC/2koGfcQgoss7W0wPrJ2klmx7j8/VSsumfWXzkiBs7KJR9meBK5xpOaP1cFeLC+lLCChYKqw++p7OHmfVYdQ2/CfqcCpJNGIMuv+P/H7W+yDbMtwqVLEboUrqPKTHBiav0lQGIFEZRZ1AYM8VNbKfjwyaVMzu7O4hojJ+r/W4TCgWd+CAnI7ea8v2U+/XMzk0H2QACthvOkSMs6S7MTk5bMELlPDzRn0hrNMl/aGJmVmVSjVKldOvo9RccGtVraq+s9PcQwwnoZZnxDGjSUjt4rJ8LzmXyZcSFyOJh9V4iD30OMgRAQl7P6x3+Nt11u8g7LEV3KfXl6BOu9b/GRIaJu/pemZn/x9V91Kj7S31fUmLwGJh/H2q8Ef3+JlmCDUwpBMNob7LNln87UUY2OSs/Lhw+O1DbHATiWZt4j+uIBdMDrwolpZDDgaUh16L5RRmJBypHolgxVyEuXnhKjwXaXTwFECWJXEXmvU=
  - secure: ajWnBtj1Vnkit5Z5/gQiw7SkdQDH/+G01jj9Ra+fPVIgzOrdvttGIF86lkgfiX4hi9CHbl7+kdT5CFNtE3XQfFUC2R/Y7cmvf1tEyp0VQ6MirEX1sye6e1iYslo4GleB02zB6f/Wy+ZmKEdJ9siuFfK9l/50pldM43wBIP1cA/9WboLGdp4oXN0fQffb+puePJGTgaRhb0LXQq35yq2egvaBXb0ASUzaZPjKpnTDIPuRoyGasT09+8ApnDXE8lu55RcRhYIoitCzWcRyCMK5apAz5dfyNxux/cz3fQbJ2LdrAwHPzvq6DyFIGndaj1+oesAv/qd7/HUxdqY0Xsq7Ce64SgcjJ5FdA3VAhWQYY/foe/2mlMzUKrb5Hft8+ON8xjssak90pO1p5Hj9oWg7+nbqyeOpuJ505Eo6/I+ryMj23JFFQJdGuHXbk1NeTTVbaSSwTvriNsV7dEYOi+++mSB+ntapenNJAo8KPHc/JcrWrm7n/3tatAMPc7ecSvZWKZCRB3GfHDJt00eRHxedZ9IT7TuPQrff6GsSSVXiGieSfQeDJmaIz7Rko7P6XUFBEctg60u19wk4WvgLm82Li75xXVY9PZE0PCksRetKzQYPA+4heejpPe1z0Px0D4WYV2zVO4Id7MEnRLPxBUPvJpcdyIOBW1HL8SaUar8oJhM=
